#!/bin/bash

[ $# -eq 1 ] || { echo "$(basename $0) <ip>"; exit 1; }

known_hosts="$HOME/.ssh/known_hosts"
grep $1 $known_hosts > /dev/null
[ $? -eq 0 ] || { echo "don't know about host $1"; exit 1; }

sed -i '' "/^$1/d" $known_hosts
